### ISSUE TITLE
Problmes with executing examples

### ISSUE THREAD

**Issue by matthiasbirkich** [mvdh7/calkulate#29]
Dear Matthew,

here there is one error message I will get with a couple of installations of Python 3.8 or 3.7:
I have installed your PyCO2SYS ver 1.5.1 and your calkulate ver. 2.3.0.
When I want to import calkulate following message occurs:
cannot import name 'assemble' from 'PyCO2SYS' (path) __init__.py

Unfortunately the package 'calkulate' is not running.
Do you have any clue about this? Thanks a lot.
best regards
Matthias

**Comment by matthiasbirkich** [comment]
Dear developers,
with Pyto on iPad I have no problems executing code with Calkulate + PyCO2sys. The only difficulty is to run external files.
best regards
Matthias

**Comment by mvdh7** [comment]
Thanks, should be fixed with v3.0.0 release now
