### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by matthiasbirkich** [mvdh7/calkulate#36]
Dear Dr. Matthew Humphrey,
thanks for the new versio of calkulate!
when I go for the metadatafile I get following output:

Calkulate:   calibrating titrant_molinity...
--
Calkulate: ERROR calibrating   'seawater-CRM-144.dat'!
Calkulate: ERROR calibrating   'filename-does-not-exist.dat'!
Calkulate: ERROR calibrating   'seawater-CRM-144-function.dat'!
Calkulate: ERROR calibrating   'Dickson-1981-pH-no_phosphate.dat'!
Calkulate: ERROR calibrating   'Dickson-1981-pH-with_phosphate.dat'!
Calkulate: calibration complete!
Calkulate: solving alkalinity...
Calkulate: ERROR solving   'seawater-CRM-144.dat'!
Calkulate: ERROR solving   'filename-does-not-exist.dat'!
Calkulate: ERROR solving   'seawater-CRM-144-function.dat'!
Calkulate: solving complete!

The data.alkalinity values are NaN

I don't have any idea what is wrong, because I am dealing with the original titration_table.csv as meatadatafile and all *.dat files are available.
best regards
Matthias

**Comment by matthiasbirkich** [comment]
[output_test_20210228.xlsx](https://github.com/mvdh7/calkulate/files/6056867/output_test_20210228.xlsx)
The reference is FALSE and the molinity will not be calculated.
This was the failing "test_dataset_io.py" script. What a pity. I am sure, it is running in your environment...
best. M

**Comment by matthiasbirkich** [comment]
Dear developers,
when we are using strictly *.csv-file formate, than no error occurs during calculation. :-).
But the solved alkalinity values are still NaN. :-(.
Are you so polite to explain, how I can calculate a single file with given molinity for DIC and Alkalinity to a Python analphabet?
It would be really great for us to implement your Calkulate package in our routine analysis.
With PyCO2 we don't have any problems and with vindta_reCALk package we are also able to recalculate our old VINDTA data.
The goal of our team is: 
Take the Dickson standard (which is NOT available at the moment) as a control and calibrate with Na2CO3-standard as it is described in the PICES 2007 document and the Vindta manual as well. Using the Dickson CRM as CONTROL is a consistent procedure in chemical analytics in our opinion. The QUASIMEME round AQ15 will go for Alkalinity and DIC.
We want to establish a possibility to be independent from Andrews CRMs, when they are not available.
For this we need to adjust the molinity according to the zero values of sulphate and fluoride, which we don't want to add to our pure Na2CO3-standard. NaCl we have to add, because of the liquid junction potential of the electrode. This circumstance we can only control with the more flexible Calkulate/PyCO2-package. What do you think about this issue? We will be glad to hear from you.

Best regards and take care
Matthias

**Comment by d-sandborn** [comment]
I have been able to replicate this issue.  Running the "Basic Use" code for the "titration_table.csv" metadatafile provided at https://calkulate.readthedocs.io/en/latest/ gives the following output in Spyder 4.1 running Python 3.7 and Calkulate 23.0.1:

> Calkulate: calibrating titrant_molinity...
> Calkulate: ERROR calibrating 'seawater-CRM-144.dat'!
> Calkulate: ERROR calibrating 'filename-does-not-exist.dat'!
> Calkulate: ERROR calibrating 'seawater-CRM-144-function.dat'!
> Calkulate: ERROR calibrating 'seawater-CRM-144-method.dat'!
> Calkulate: ERROR calibrating 'Dickson-1981-pH-no_phosphate.dat'!
> Calkulate: ERROR calibrating 'Dickson-1981-pH-with_phosphate.dat'!
> Calkulate: calibration complete!
> Calkulate: solving alkalinity...
> Calkulate: solving complete!

I saved the resulting dataframe and attached it below.
[data.txt](https://github.com/mvdh7/calkulate/files/6073049/data.txt)

I've also been wrestling with similar problems over the last week or two.  I have not yet found a repeatable way to modify the titration metadata table to calculate alkalinity successfully.  I'll keep working on this.

**Comment by matthiasbirkich** [comment]
Dear developers, 
now I am able to work with the program. I studied the "test_dataset_manual.py" and understood:
I haven't put a value to "alkalinity_certified" for the samples, which I wanted to calculate for alkalinity.
In all other programs (seacarb, Dicksons Gran-plot, others) it is not necessary.
Sorry, that I put that issue into this channel. I would like to apologize for this behavior.
One question:
Is it planned to go for the calculation of DIC as well, like the publication of Dickson D81 with the itterative method?
That would be really great.
best regards
Matthias
